# Generated by Django 4.2.7 on 2026-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category_alter_recipe_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_steps',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='steps/'),
        ),
    ]
